### PR TITLE
Functions for adding and removing blacklist entries

### PR DESCRIPTION
**Pull request by elffjs**
# Proposed Changes

### CODE REVIEW

**Comment by elffjs** [comment]
@Asfiroth Does the shape of this look okay to you?

**Comment by Asfiroth** [comment]
> @Asfiroth Does the shape of this look okay to you?
 Yes @elffjs this is mostly what is needed

**Comment by elffjs** [comment]
> mostly

Anything else you would want brader @Asfiroth

**Comment by Asfiroth** [comment]
> > mostly
> 
> Anything else you would want brader @Asfiroth

there's this `CIO which would auto-trigger an email to users letting them know they did not get rewards and to provide verification that they own the vehicle` but i don't think that goes here, so that would be all of it 
@elffjs

**Pull request merged**
